version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  service1:
    image: blakelewis1/service-1:latest
    build: ./s1
    ports:
    - target: 8000
      published: 8000
    environment:
    - PGN_DB=${PGN_DB}
  service2:
    image: blakelewis1/service-2:latest
    build: ./s2
    ports:
    - target: 8001
      published: 8001
    environment:
    - PGN_DB=${PGN_DB}
  service3:
    image: blakelewis1/service-3:latest
    build: ./s3
    ports:
    - target: 8002
      published: 8002
    environment:
    - PGN_DB=${PGN_DB}
  service4:
    image: blakelewis1/service-4:latest
    build: ./s4
    ports:
    - target: 8003
      published: 8003
    environment:
    - PGN_DB=${PGN_DB}
