- name: install docker
  hosts: manager_node
  become: true
  roles:
    - docker_install

- name: initialise docker swarm
  hosts: manager_node
  become: true
  roles:
    - docker_swarm

- name: add workers to the swarm
  hosts: node1
  become: true
  roles:
    - docker_workers